"""Defines all the URIs"""

TariffCreateUri = "/tariff"
TariffUpdateUri = "/tariff/{tariff_id}"
TariffGeneratedRateCreateUri = "/tariff_generated_rate"
DoeCreateUri = "/doe"
SiteUri = "/site"
SiteGroupUri = "/site_group/{group_name}"
SiteGroupListUri = "/site_group"
BillingUri = "/billing/aggregator/{aggregator_id}/tariff/{tariff_id}/period/{period_start}/{period_end}"
